TEMPLATE = app

QT += qml quick
CONFIG += c++11

SOURCES += main.cpp \
    modules/cameracalibrator.cpp \
    modules/csvdatastreamer.cpp \
    modules/objecttracker.cpp \
    modules/roadhomography.cpp \
    filemanager.cpp \
    frameprocessingpipeline.cpp \
    frameprocessingpipelinefactory.cpp \
    frameprovider.cpp \
    roaddrawer.cpp \
    trafficcounter.cpp \
    videofeed.cpp \
    pipelinethreading.cpp

RESOURCES += qml.qrc

# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH =

# Additional import path used to resolve QML modules just for Qt Quick Designer
QML_DESIGNER_IMPORT_PATH =

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0
INCLUDEPATH += $${PWD}\\libs\\opencv3vc14\\opencv\\build\\include

LIBS += "-L$${PWD}\\libs\\opencv3vc14\\opencv\\build\\x64\\vc14\\lib" -lopencv_world320d




# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target


HEADERS += \
    blob-tracking/blob.h \
    blob-tracking/BlobTracker.h \
    interfaces/ifframefeed.h \
    interfaces/ifobjecttracker.h \
    interfaces/ifprocessframe.h \
    interfaces/iftrackeddatastream.h \
    libs/opencv3vc14/opencv/build/include/opencv/cv.h \
    libs/opencv3vc14/opencv/build/include/opencv/cv.hpp \
    libs/opencv3vc14/opencv/build/include/opencv/cvaux.h \
    libs/opencv3vc14/opencv/build/include/opencv/cvaux.hpp \
    libs/opencv3vc14/opencv/build/include/opencv/cvwimage.h \
    libs/opencv3vc14/opencv/build/include/opencv/cxcore.h \
    libs/opencv3vc14/opencv/build/include/opencv/cxcore.hpp \
    libs/opencv3vc14/opencv/build/include/opencv/cxeigen.hpp \
    libs/opencv3vc14/opencv/build/include/opencv/cxmisc.h \
    libs/opencv3vc14/opencv/build/include/opencv/highgui.h \
    libs/opencv3vc14/opencv/build/include/opencv/ml.h \
    libs/opencv3vc14/opencv/build/include/opencv2/calib3d/calib3d.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/calib3d/calib3d_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/core/hal/hal.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/hal/interface.h \
    libs/opencv3vc14/opencv/build/include/opencv2/core/hal/intrin.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/hal/intrin_cpp.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/hal/intrin_neon.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/hal/intrin_sse.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/affine.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/base.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/bufferpool.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/core.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/core_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cuda.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cuda.inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cuda_stream_accessor.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cuda_types.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cvdef.h \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cvstd.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cvstd.inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/directx.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/eigen.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/fast_math.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/ippasync.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/mat.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/mat.inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/matx.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/neon_utils.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/ocl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/ocl_genbase.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/opengl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/operations.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/optim.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/ovx.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/persistence.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/private.cuda.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/private.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/ptr.inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/saturate.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/sse_utils.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/traits.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/types.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/types_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/core/utility.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/va_intel.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/version.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/wimage.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/features2d/features2d.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/all_indices.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/allocator.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/any.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/autotuned_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/composite_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/config.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/defines.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/dist.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/dummy.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/dynamic_bitset.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/flann.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/flann_base.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/general.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/ground_truth.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/hdf5.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/heap.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/hierarchical_clustering_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/index_testing.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/kdtree_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/kdtree_single_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/kmeans_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/linear_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/logger.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/lsh_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/lsh_table.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/matrix.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/miniflann.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/nn_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/object_factory.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/params.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/random.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/result_set.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/sampling.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/saving.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/simplex_downhill.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/timer.h \
    libs/opencv3vc14/opencv/build/include/opencv2/highgui/highgui.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/highgui/highgui_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/imgcodecs/imgcodecs.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/imgcodecs/imgcodecs_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/imgcodecs/ios.h \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc/detail/distortion_model.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc/hal/hal.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc/hal/interface.h \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc/imgproc.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc/imgproc_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc/types_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/ml/ml.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/objdetect/detection_based_tracker.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/objdetect/objdetect.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/objdetect/objdetect_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/photo/cuda.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/photo/photo.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/photo/photo_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/shape/emdL1.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/shape/hist_cost.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/shape/shape.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/shape/shape_distance.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/shape/shape_transformer.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/autocalib.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/blenders.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/camera.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/exposure_compensate.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/matchers.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/motion_estimators.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/seam_finders.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/timelapsers.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/util.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/util_inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/warpers.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/warpers_inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/warpers.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/superres/optical_flow.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/video/background_segm.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/video/tracking.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/video/tracking_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/video/video.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videoio/cap_ios.h \
    libs/opencv3vc14/opencv/build/include/opencv2/videoio/videoio.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videoio/videoio_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/deblurring.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/fast_marching.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/fast_marching_inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/frame_source.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/global_motion.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/inpainting.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/log.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/motion_core.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/motion_stabilizing.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/optical_flow.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/outlier_rejection.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/ring_buffer.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/stabilizer.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/wobble_suppression.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/calib3d.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/cvconfig.h \
    libs/opencv3vc14/opencv/build/include/opencv2/features2d.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/flann.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/highgui.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/imgcodecs.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/ml.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/objdetect.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/opencv.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/opencv_modules.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/photo.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/shape.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/superres.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/video.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videoio.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/world.hpp \
    modules/cameracalibrator.h \
    modules/csvdatastreamer.h \
    modules/objecttracker.h \
    modules/roadhomography.h \
    filemanager.h \
    frameprocessingpipeline.h \
    frameprocessingpipelinefactory.h \
    frameprovider.h \
    roaddrawer.h \
    trafficcounter.h \
    videofeed.h \
    blob-tracking/blob.h \
    blob-tracking/BlobTracker.h \
    interfaces/ifframefeed.h \
    interfaces/ifobjecttracker.h \
    interfaces/ifprocessframe.h \
    interfaces/iftrackeddatastream.h \
    libs/opencv3vc14/opencv/build/include/opencv/cv.h \
    libs/opencv3vc14/opencv/build/include/opencv/cv.hpp \
    libs/opencv3vc14/opencv/build/include/opencv/cvaux.h \
    libs/opencv3vc14/opencv/build/include/opencv/cvaux.hpp \
    libs/opencv3vc14/opencv/build/include/opencv/cvwimage.h \
    libs/opencv3vc14/opencv/build/include/opencv/cxcore.h \
    libs/opencv3vc14/opencv/build/include/opencv/cxcore.hpp \
    libs/opencv3vc14/opencv/build/include/opencv/cxeigen.hpp \
    libs/opencv3vc14/opencv/build/include/opencv/cxmisc.h \
    libs/opencv3vc14/opencv/build/include/opencv/highgui.h \
    libs/opencv3vc14/opencv/build/include/opencv/ml.h \
    libs/opencv3vc14/opencv/build/include/opencv2/calib3d/calib3d.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/calib3d/calib3d_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/core/hal/hal.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/hal/interface.h \
    libs/opencv3vc14/opencv/build/include/opencv2/core/hal/intrin.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/hal/intrin_cpp.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/hal/intrin_neon.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/hal/intrin_sse.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/affine.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/base.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/bufferpool.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/core.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/core_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cuda.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cuda.inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cuda_stream_accessor.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cuda_types.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cvdef.h \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cvstd.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/cvstd.inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/directx.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/eigen.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/fast_math.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/ippasync.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/mat.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/mat.inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/matx.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/neon_utils.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/ocl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/ocl_genbase.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/opengl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/operations.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/optim.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/ovx.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/persistence.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/private.cuda.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/private.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/ptr.inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/saturate.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/sse_utils.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/traits.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/types.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/types_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/core/utility.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/va_intel.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/version.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core/wimage.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/features2d/features2d.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/all_indices.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/allocator.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/any.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/autotuned_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/composite_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/config.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/defines.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/dist.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/dummy.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/dynamic_bitset.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/flann.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/flann_base.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/general.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/ground_truth.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/hdf5.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/heap.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/hierarchical_clustering_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/index_testing.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/kdtree_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/kdtree_single_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/kmeans_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/linear_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/logger.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/lsh_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/lsh_table.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/matrix.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/miniflann.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/nn_index.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/object_factory.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/params.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/random.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/result_set.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/sampling.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/saving.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/simplex_downhill.h \
    libs/opencv3vc14/opencv/build/include/opencv2/flann/timer.h \
    libs/opencv3vc14/opencv/build/include/opencv2/highgui/highgui.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/highgui/highgui_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/imgcodecs/imgcodecs.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/imgcodecs/imgcodecs_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/imgcodecs/ios.h \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc/detail/distortion_model.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc/hal/hal.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc/hal/interface.h \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc/imgproc.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc/imgproc_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc/types_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/ml/ml.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/objdetect/detection_based_tracker.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/objdetect/objdetect.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/objdetect/objdetect_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/photo/cuda.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/photo/photo.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/photo/photo_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/shape/emdL1.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/shape/hist_cost.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/shape/shape.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/shape/shape_distance.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/shape/shape_transformer.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/autocalib.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/blenders.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/camera.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/exposure_compensate.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/matchers.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/motion_estimators.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/seam_finders.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/timelapsers.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/util.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/util_inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/warpers.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/detail/warpers_inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching/warpers.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/superres/optical_flow.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/video/background_segm.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/video/tracking.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/video/tracking_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/video/video.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videoio/cap_ios.h \
    libs/opencv3vc14/opencv/build/include/opencv2/videoio/videoio.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videoio/videoio_c.h \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/deblurring.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/fast_marching.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/fast_marching_inl.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/frame_source.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/global_motion.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/inpainting.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/log.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/motion_core.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/motion_stabilizing.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/optical_flow.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/outlier_rejection.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/ring_buffer.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/stabilizer.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab/wobble_suppression.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/calib3d.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/core.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/cvconfig.h \
    libs/opencv3vc14/opencv/build/include/opencv2/features2d.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/flann.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/highgui.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/imgcodecs.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/imgproc.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/ml.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/objdetect.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/opencv.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/opencv_modules.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/photo.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/shape.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/stitching.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/superres.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/video.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videoio.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/videostab.hpp \
    libs/opencv3vc14/opencv/build/include/opencv2/world.hpp \
    modules/cameracalibrator.h \
    modules/csvdatastreamer.h \
    modules/objecttracker.h \
    modules/roadhomography.h \
    filemanager.h \
    frameprocessingpipeline.h \
    frameprocessingpipelinefactory.h \
    frameprovider.h \
    roaddrawer.h \
    trafficcounter.h \
    videofeed.h \
    pipelinethreading.h
